class TypeWidthModel {
  /*
  generated by https://javiercbk.github.io/json_to_dart/
   */
  String treadType = '';
  List<String> treadWidth = [''];

  TypeWidthModel({required this.treadType, required this.treadWidth});

  TypeWidthModel.fromJson(Map<String, dynamic> json) {
    treadType = json['treadType'];
    treadWidth = json['treadWidth'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['treadType'] = treadType;
    data['treadWidth'] = treadWidth;
    return data;
  }
}